apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-app-sample-production
  namespace: flux-app-production
spec:
  releaseName: gitops-app-sample-production
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: gitops-app-sample
        namespace: flux-app
      valuesFiles:
      - values.yaml
      - values-production.yaml
      values:
        image:
          tag: latest
  interval: 1m
