apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-app-sample-dev
  namespace: flux-app-dev
spec:
  releaseName: gitops-app-sample-dev
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: gitops-app-sample
        namespace: flux-app
      valuesFiles:
      - ./helm/values.yaml
      - ./helm/values-dev.yaml
  values:
    image:
      tag: "c7035b5f441acb3388f8b9b5938fda8993e81ee3"
  interval: 1m
