apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-app-sample-dev
  namespace: flux-app-dev
spec:
  releaseName: gitops-app-sample-dev
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: gitops-app-sample
        namespace: flux-app
      valuesFiles:
      - values.yaml
      - values-dev.yaml
      values:
        image:
          tag: latest
  interval: 1m
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-app-sample-dev
  namespace: flux-app-dev
spec:
  releaseName: gitops-app-sample-dev
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: gitops-app-sample
        namespace: flux-app
      valuesFiles:
      - values.yaml
      - values-dev.yaml
      values:
        image:
          tag: "a98cafd6c4a40721698e8df7046ac37870ed2240"
  interval: 1m
