apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-app-sample-staging
  namespace: flux-app-staging
spec:
  releaseName: gitops-app-sample-staging
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: gitops-app-sample
        namespace: flux-app
      valuesFiles:
      - ./helm/values.yaml
      - ./helm/values-staging.yaml
  values:
    image:
      tag: "b58c2624451149740218a6c40dce8931500163fc"
  interval: 1m
