apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-app-sample-staging
  namespace: flux-app-staging
spec:
  releaseName: gitops-app-sample-staging
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: gitops-app-sample
        namespace: flux-app
      valuesFiles:
      - ./values.yaml
      - ./values-staging.yaml
  values:
    image:
      tag: "934355d25292c5b30b44e15435188e3e12bc8fbe"
  interval: 1m
